# Generated by Django 4.0.6 on 2022-07-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='customer',
        ),
    ]
