# Generated by Django 4.0.6 on 2022-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customers_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PhoneNum',
            new_name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='Address_Line1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='Address_Line2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
