# Generated by Django 4.0.6 on 2022-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_firstname_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address_Line1',
            field=models.CharField(max_length=500),
        ),
    ]
