# Generated by Django 4.0.6 on 2022-07-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_address_line1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address_Line2',
            field=models.CharField(max_length=500),
        ),
    ]
