# Generated by Django 4.0.6 on 2022-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_address_line2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address_Line2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
