# Generated by Django 4.0.6 on 2022-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_address_line2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
    ]
